name: CI

on: [push, pull_request]

jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['8.1', '8.2', '8.3']
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  tools: composer:v2, phpunit:10.0

            - name: Install dependencies
              run: composer install --prefer-dist

            - name: Run tests
              run: phpunit
